version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_log:/var/log/postgresql
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "9097:5432"

volumes:
  postgres_data: