version: "3.9"
services:
  grafana:
    image: grafana/grafana
    ports:
      - 9093:3000
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  postgres:
    image: postgres:latest
    ports:
      - 9091:5432
    volumes:
      - ./backup:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: shop
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9092:9187
    environment:
      # DATA_SOURCE_NAME: "postgresql://postgres:postgrespassword@postgres:9091/shop?sslmode=disable"    legacy way
      DATA_SOURCE_URI: "localhost:9091/shop?sslmode=disable"
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS: postgrespassword
    links:
      - postgres
      - prometheus