version: '3.1'

services:
  postgres-master:
    image: postgres:15
    environment: 
      POSTGRES_USER: masteruser
      POSTGRES_PASSWORD: masterpass
      POSTGRES_DB: masterdb
    ports:
      - "9096:5432"
    volumes:
      - ./master-data:/var/lib/postgresql/data

  postgres-replica:
    image: postgres:15
    environment: 
      POSTGRES_USER: replicauser
      POSTGRES_PASSWORD: replicapass
      POSTGRES_DB: replicadb
    ports:
      - "9097:5432"
    volumes:
      - ./replica-data:/var/lib/postgresql/data